server.port=8080
spring.application.name=ewm-main-service
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/ewm}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ewm_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ewm_pass}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
stats-server.url=${STATS_SERVER_URL:http://localhost:9090}